[project]
name = "music-streaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual[syntax]>=3.5.0",
    "textual-dev>=1.7.0",
    "yt-dlp>=2025.6.30",
    "mpv>=1.0.8",
]
